In [1]:
import numpy as np
import matplotlib
from sklearn import datasets

In [2]:
digits = datasets.load_digits()

In [3]:
digits.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [4]:
print(digits.DESCR)

Optical Recognition of Handwritten Digits Data Set

Notes
-----
Data Set Characteristics:
    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
http://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each block. This generates
an input matrix of 8x8 where each element is a

In [5]:
X = digits.data
X.shape

(1797, 64)

In [6]:
y = digits.target
y.shape

(1797,)

In [7]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y[:20]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
X[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [10]:
some_digit = X[888]
y[888]

7

In [11]:
some_digit_image = some_digit.reshape(8,8)

In [12]:
import matplotlib.pyplot as plt 
plt.imshow(some_digit_image,cmap=matplotlib.cm.binary)

In [13]:
from KNN.model_selection import train_test_split

In [14]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_ratio=0.2)

In [15]:
from KNN.KNN_adver import KNNClassifier

In [16]:
my_knn_clf = KNNClassifier(k=3)

In [17]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [18]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([7, 6, 4, 2, 5, 0, 4, 3, 4, 5, 5, 7, 9, 9, 1, 3, 7, 4, 1, 0, 8, 5,
       7, 6, 0, 5, 4, 3, 4, 6, 8, 2, 7, 7, 9, 8, 4, 9, 2, 8, 5, 6, 3, 7,
       8, 6, 7, 9, 1, 0, 0, 3, 4, 0, 4, 3, 4, 6, 7, 5, 6, 2, 7, 7, 6, 1,
       4, 4, 9, 9, 4, 4, 7, 1, 3, 4, 1, 3, 1, 2, 0, 0, 6, 9, 1, 2, 4, 6,
       2, 7, 1, 6, 1, 2, 9, 2, 2, 0, 4, 8, 8, 3, 7, 2, 2, 9, 9, 7, 8, 1,
       2, 9, 2, 9, 6, 8, 0, 9, 6, 8, 0, 4, 5, 6, 8, 4, 3, 2, 2, 0, 5, 7,
       2, 3, 6, 5, 8, 5, 4, 8, 5, 4, 8, 3, 3, 1, 7, 9, 6, 0, 6, 5, 7, 1,
       3, 3, 9, 8, 2, 1, 3, 9, 3, 0, 6, 1, 5, 1, 1, 8, 7, 7, 4, 1, 3, 2,
       3, 3, 6, 2, 7, 6, 9, 9, 9, 6, 5, 6, 9, 8, 0, 0, 6, 1, 9, 3, 6, 3,
       7, 8, 2, 2, 2, 1, 3, 0, 1, 4, 9, 4, 6, 3, 2, 3, 4, 8, 2, 9, 1, 2,
       9, 1, 9, 2, 4, 1, 9, 7, 7, 4, 7, 1, 4, 2, 2, 5, 5, 8, 6, 1, 7, 8,
       3, 7, 7, 9, 4, 4, 9, 5, 5, 5, 1, 5, 8, 0, 3, 1, 6, 6, 7, 9, 3, 7,
       1, 4, 4, 0, 5, 1, 7, 1, 2, 2, 0, 8, 3, 1, 3, 0, 0, 9, 2, 1, 0, 5,
       9, 7, 9, 5, 0, 9, 2, 2, 9, 2, 6, 0, 3, 8, 7,

In [19]:
y_test

array([7, 6, 4, 2, 5, 0, 4, 3, 4, 5, 5, 7, 9, 9, 1, 3, 7, 4, 1, 0, 8, 5,
       7, 6, 0, 5, 4, 3, 4, 6, 8, 2, 7, 7, 9, 8, 4, 9, 2, 8, 5, 6, 3, 7,
       8, 6, 7, 9, 1, 0, 0, 3, 4, 0, 4, 3, 4, 6, 7, 5, 6, 2, 7, 7, 6, 1,
       4, 4, 9, 9, 4, 4, 7, 1, 3, 4, 1, 3, 1, 2, 0, 0, 6, 9, 1, 2, 4, 6,
       2, 7, 1, 6, 1, 2, 9, 2, 2, 0, 4, 8, 8, 3, 7, 2, 2, 9, 9, 7, 8, 1,
       2, 9, 2, 9, 6, 8, 0, 9, 6, 8, 0, 4, 5, 6, 8, 4, 3, 2, 2, 0, 5, 7,
       2, 3, 6, 5, 8, 5, 4, 8, 5, 4, 8, 3, 3, 1, 7, 9, 6, 0, 6, 5, 7, 1,
       3, 3, 9, 8, 2, 1, 3, 9, 3, 0, 6, 1, 5, 1, 1, 8, 7, 7, 4, 1, 3, 2,
       3, 3, 6, 2, 7, 6, 9, 9, 9, 6, 5, 6, 9, 8, 0, 0, 6, 1, 9, 3, 6, 3,
       7, 8, 2, 2, 2, 1, 3, 0, 1, 4, 9, 4, 6, 3, 2, 3, 4, 8, 2, 9, 1, 2,
       9, 1, 9, 2, 4, 1, 9, 7, 7, 4, 7, 1, 4, 2, 2, 5, 5, 8, 6, 1, 7, 8,
       3, 7, 7, 9, 4, 4, 5, 5, 5, 5, 1, 5, 8, 0, 3, 1, 6, 6, 7, 9, 3, 7,
       1, 4, 4, 0, 5, 1, 7, 1, 2, 2, 0, 8, 3, 1, 3, 0, 0, 9, 2, 1, 0, 5,
       9, 7, 9, 5, 0, 9, 2, 2, 9, 2, 6, 0, 3, 8, 7,

In [20]:
sum(y_predict == y_test) / len(y_test)

0.9972144846796658

In [21]:
from KNN.metrics import accuracy_score

In [22]:
accuracy_score(y_test,y_predict)

0.9972144846796658

In [24]:
my_knn_clf.score(X_test,y_test)

0.9972144846796658

### scikit-learn 中的accuracy_score

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=88)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

knn_clf = KNeighborsClassifier(n_neighbors=3)

In [28]:
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [30]:
y_predict = knn_clf.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predict)

0.9805555555555555

In [32]:
knn_clf.score(X_test, y_test)

0.9805555555555555