In [20]:
import numpy as np
x = np.random.normal(0,1,size=100000)

### 索引

In [21]:
np.min(x)

-4.604912822588419

如何获取最小是的索引？

In [22]:
np.argmin(x)

19355

In [23]:
x[3137]

-0.40383443228171184

In [24]:
np.argmax(x)

80718

In [25]:
x[16091]

0.18412559068042555

In [26]:
np.max(x)

4.812976531610483

### 排序和使用索引

In [27]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.random.shuffle(x)

In [29]:
x

array([ 4,  3,  2, 13, 15,  5,  0, 11, 14, 12,  6, 10,  9,  8,  1,  7])

shuffle对数字进行乱序

In [30]:
x.sort()

In [31]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

对象上操作和x上操作是不一样的

In [32]:
x = np.random.randint(10,size=(4,4))

In [33]:
np.sort(x)

array([[0, 0, 2, 7],
       [3, 4, 9, 9],
       [4, 5, 8, 9],
       [6, 7, 8, 8]])

默认是对每一行进行排序

In [34]:
np.sort(x,axis=1)

array([[0, 0, 2, 7],
       [3, 4, 9, 9],
       [4, 5, 8, 9],
       [6, 7, 8, 8]])

In [35]:
np.sort(x,axis=0)

array([[0, 3, 0, 2],
       [6, 4, 4, 7],
       [8, 7, 5, 9],
       [9, 8, 8, 9]])

In [45]:
x= np.arange(16)
np.random.shuffle(x)

In [48]:
np.argsort(x)

array([13,  2, 11,  5,  7,  0, 10,  3, 12,  8,  9, 15,  6,  4, 14,  1],
      dtype=int64)

快速排序

In [49]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5, 12, 15,  9, 10,  6, 13,  8,  7, 14, 11])

3前面的比3小，但是是无序的

In [50]:
np.argpartition(x,3)

array([13,  2, 11,  5,  7,  0,  6,  1,  8,  9, 10,  4, 12,  3, 14, 15],
      dtype=int64)