### 合并操作

In [12]:
import numpy as np

In [13]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [14]:
x

array([1, 2, 3])

In [15]:
y

array([3, 2, 1])

In [16]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [17]:
z = np.array([888,888,888])

In [18]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 888, 888, 888])

#### 对于矩阵

In [19]:
A = np.array([[1,2,3],
              [4,5,6]])

In [20]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [21]:
np.concatenate([A,A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### 对于维数不一样的,先进行维数的变化

In [22]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [888, 888, 888]])

In [23]:
A2 = np.concatenate([A,z.reshape(1,-1)])
A2

array([[  1,   2,   3],
       [  4,   5,   6],
       [888, 888, 888]])

其实可以不用更实用reshape

In [24]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [888, 888, 888]])

In [25]:
B = np.full((2,2),100)

In [26]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x1,x2,x3 = np.split(x,[3,7])

In [29]:
x1

array([0, 1, 2])

In [30]:
x2

array([3, 4, 5, 6])

In [31]:
x3

array([7, 8, 9])

In [32]:
x4,x5 = np.split(x,[5])

In [33]:
x4

array([0, 1, 2, 3, 4])

In [34]:
x5

array([5, 6, 7, 8, 9])

In [35]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
a1,a2 = np.split(A,[2])

In [37]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [38]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

说明默认是基于行进行分割

In [39]:
a1,a2 = np.split(A,[2],axis=1)

In [40]:
a1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [41]:
a2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

上面的方法不直观，使用下面的方法

In [43]:
upper,lower = np.vsplit(A,[2])

In [44]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [45]:
left ,right = np.hsplit(A,[2])

In [46]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [48]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
X, w = np.hsplit(data, [-1])

In [57]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [59]:
w

array([[ 3],
       [ 7],
       [11],
       [15]])

上面的将最后一列与前面的分割