In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
L

array([0.19218537, 0.41642352, 0.23594032, 0.52700181, 0.99363815,
       0.99803789, 0.16317324, 0.1127822 , 0.60738242, 0.39467088,
       0.04432666, 0.58214229, 0.00115678, 0.90594187, 0.32175393,
       0.64098858, 0.90955081, 0.46910504, 0.70484823, 0.19362263,
       0.51888828, 0.38844877, 0.69628627, 0.20142029, 0.7541623 ,
       0.84885224, 0.69128872, 0.73864163, 0.70492502, 0.33369325,
       0.52650185, 0.96260171, 0.30193654, 0.52826393, 0.50372631,
       0.89009077, 0.24226645, 0.83016105, 0.24257776, 0.55736672,
       0.25047278, 0.26553267, 0.21652297, 0.88251725, 0.91706048,
       0.2052981 , 0.29043488, 0.62237907, 0.7668395 , 0.83690381,
       0.17819036, 0.80650696, 0.38514346, 0.82519467, 0.74743446,
       0.55584343, 0.92118753, 0.87283819, 0.32347498, 0.06328172,
       0.21986267, 0.87028739, 0.06262596, 0.67110992, 0.67195679,
       0.79701771, 0.95953292, 0.63705273, 0.93348185, 0.55976387,
       0.4984848 , 0.81704717, 0.51289775, 0.84837333, 0.46768

In [4]:
sum(L)

53.73316822398979

In [5]:
np.sum(L)

53.73316822398979

In [6]:
big_array = np.random.rand(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

18.6 ms ± 109 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
75.7 µs ± 852 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
np.min(big_array)

5.57149802704604e-06

In [8]:
np.max(big_array)

0.9999712434353003

In [9]:
big_array.min()

5.57149802704604e-06

In [10]:
big_array.sum()

50020.52271682777

推荐使用np.min()

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

求莫一行的值或某一列的值

In [13]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [14]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

axis=0把行压缩调

In [15]:
np.prod(X)

0

In [16]:
np.prod(X+1)

2004189184

In [17]:
np.mean(X)

7.5

In [18]:
np.median(X)

7.5

In [20]:
v = np.array([1,1,2,2,10])
np.mean(v)

3.2

In [21]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)

0.5002604932249983

In [23]:
np.median(big_array)

0.5002604932249983

百分位

In [24]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array, q=percent))

5.57149802704604e-06
0.2482149396928673
0.5002604932249983
0.7519410824988004
0.9999712434353003


方差

In [25]:
np.var(big_array)

0.08373176772034262

标准数

In [26]:
np.std(big_array)

0.28936442027371406

In [27]:
x = np.random.normal(0,1,size=10000)
np.mean(x)

-0.02091964931188652

In [28]:
np.std(x)

0.9861993922001897